version: "3"

services:
  talent.spa:
    image: mvpstudionz/talent.spa:dev
    environment:
      - TALENT_APP_API_URL=http://192.168.99.100:60002 # change the localhost to 192.168.99.100 if you're using docker toolbox
      - TALENT_APP_IDENTITY_API_URL=http://192.168.99.100:60001 # change the localhost to 192.168.99.100 if you're using docker toolbox
    ports:
      - "3000:5034"
  talent.services.identity:
    image: mvpstudionz/talent.services.identity:dev
    ports:
      - "60001:60998"
  talent.api:
    image: mvpstudionz/talent.api:dev
    ports:
      - "60002:60880"
